### ISSUE TITLE
PHP: about vhost_file

### ISSUE THREAD

**Issue by kinosang** [tsuru/basebuilder#62]
@sroze 
Here's my tsuru.yaml

```
php:
    frontend:
        name: nginx
        vhost_file: /home/application/current/vhost.conf
    interpretor:
        name: fpm54
    composer: false
```

I've also tried

```
php:
    frontend:
        name: nginx
        nginx:
            vhost_file: /home/application/current/vhost.conf
    interpretor:
        name: fpm54
    composer: false
```

I wonder why the `vhost_file` not effective.
